name: RDRHC Calendar Testing

on: [push]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv run python -m pip install -U pip
        pipenv install --dev --ignore-pipfile
    - name: Run tests
      run: |
        pipenv run pytest --cov=modules --cov-report=xml
    - name: Submit test coverage
      uses: codecov/codecov-action@v2
      with:
        files: ./reports/coverage.xml
        flags: unittests
        name: studybuffalo-coverage
        fail_ci_if_error: true
        verbose: true
    - name: Run linters
      run: |
        pipenv run pylint run.py modules/
        pipenv run pylint tests/ --min-similarity-lines=20
        pipenv run pycodestyle run.py modules/ tests/
